# Generated by Django 5.2.8 on 2025-11-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_inventory', '0002_tag_product_is_active_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Set this HIGHER than Selling Price to show a discount (e.g. ~~1200~~ 1000).', max_digits=10, null=True, verbose_name='Original / Market Price'),
        ),
    ]
