# Generated by Django 5.2.8 on 2025-11-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_inventory', '0003_product_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_seo_optimized',
            field=models.BooleanField(default=False, help_text='True if AI has processed this.'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Manual override for SEO Description', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_ai',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Manual override for SEO Title', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title_ai',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
