# Generated by Django 5.2.8 on 2025-11-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_inventory', '0004_product_is_seo_optimized_product_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ai_suggested_description',
            field=models.TextField(blank=True, help_text='AI generated description tailored for Bangladeshi audience.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ai_suggested_name',
            field=models.CharField(blank=True, help_text='AI generated product name based on image & attributes.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='use_ai_description',
            field=models.BooleanField(default=False, help_text="If checked, the website will show 'AI Suggested Description' instead of the manual 'Description'.", verbose_name='Use AI Description on Frontend'),
        ),
        migrations.AddField(
            model_name='product',
            name='use_ai_name',
            field=models.BooleanField(default=False, help_text="If checked, the website will show 'AI Suggested Name' instead of the manual 'Name'.", verbose_name='Use AI Name on Frontend'),
        ),
    ]
