# Generated by Django 5.2.8 on 2025-11-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_inventory', '0005_product_ai_suggested_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ai_suggested_category',
            field=models.CharField(blank=True, help_text='AI suggested category name. Admin must approve to apply.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ai_suggested_tags',
            field=models.TextField(blank=True, help_text="Comma-separated list of AI suggested tags (e.g. 'Summer, Cotton, Sale').", null=True),
        ),
    ]
