# Generated by Django 5.2.8 on 2025-11-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_inventory', '0006_product_ai_suggested_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ai_suggested_short_description',
            field=models.TextField(blank=True, help_text='AI generated summary (HTML allowed).', null=True),
        ),
    ]
