# Generated by Django 5.2.8 on 2025-11-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_inventory', '0007_product_ai_suggested_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='use_ai_short_description',
            field=models.BooleanField(default=False, verbose_name='Use AI Short Desc'),
        ),
    ]
