# Generated by Django 5.2.8 on 2025-12-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_inventory', '0008_product_use_ai_short_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariation',
            options={'verbose_name': 'Variation', 'verbose_name_plural': 'Variations'},
        ),
        migrations.AddField(
            model_name='productvariation',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Set higher than selling price to show discount for this specific variation.', max_digits=10, null=True, verbose_name='Original Price'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='name',
            field=models.CharField(help_text='e.g. Size: XL, Color: Red', max_length=255, verbose_name='Variation Name'),
        ),
    ]
