# Generated by Django 5.2.8 on 2025-12-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_inventory', '0009_alter_productvariation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='image',
            field=models.ImageField(blank=True, help_text='Specific image for this variation (e.g. Red Shirt). Used in Landing Page/Cart.', null=True, upload_to='products/variations/', verbose_name='Variation Image'),
        ),
    ]
