# Generated by Django 5.2.8 on 2025-12-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_inventory', '0010_productvariation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='placeholder',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='image_placeholder',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
