# Generated by Django 5.2.8 on 2025-12-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_inventory', '0011_productimage_placeholder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Uncheck to hide this product from the frontend without deleting it.', verbose_name='Visible in Store'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Check this to show on Homepage Hero section', verbose_name='Is Featured'),
        ),
    ]
