# Generated by Django 5.2.8 on 2025-12-14 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_inventory', '0012_alter_product_is_active_alter_product_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_type', models.CharField(choices=[('COLOR', 'Color'), ('SIZE', 'Size'), ('MATERIAL', 'Material'), ('STYLE', 'Style'), ('OTHER', 'Other')], help_text='Type of variation (color, size, etc.)', max_length=20, verbose_name='Variant Type')),
                ('name', models.CharField(help_text="e.g., 'Red', 'Large', 'Cotton'", max_length=100, verbose_name='Variant Name')),
                ('color_code', models.CharField(blank=True, help_text='Hex color code (e.g., #FF0000) for visual display', max_length=7, null=True, verbose_name='Color Code')),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0.0, help_text='Additional cost for this variant (can be negative for discounts)', max_digits=10, verbose_name='Price Adjustment')),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Available stock for this specific variant', verbose_name='Stock Quantity')),
                ('sku', models.CharField(blank=True, help_text='Unique identifier for this variant', max_length=100, null=True, unique=True, verbose_name='SKU')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this variant without deleting it', verbose_name='Is Active')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first', verbose_name='Sort Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='jeba_inventory.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'db_table': 'jeba_inventory_product_variant',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('product', 'variant_type', 'name')},
            },
        ),
    ]
