# Generated by Django 5.2.8 on 2025-12-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500, verbose_name='Tested URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_time_ms', models.IntegerField(default=0, help_text='Total response time in ms')),
                ('ttfb_ms', models.IntegerField(default=0, help_text='Time to First Byte in ms')),
                ('download_time_ms', models.IntegerField(default=0, help_text='Content download time in ms')),
                ('html_size_bytes', models.IntegerField(default=0)),
                ('total_assets_size_bytes', models.IntegerField(default=0)),
                ('image_count', models.IntegerField(default=0)),
                ('script_count', models.IntegerField(default=0)),
                ('css_count', models.IntegerField(default=0)),
                ('details', models.JSONField(default=dict)),
                ('performance_score', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
