# Generated by Django 5.2.8 on 2025-11-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bkash_number', models.CharField(default='017XXXXXXXX', help_text='Personal bKash Number for manual payments', max_length=15)),
                ('delivery_charge_inside', models.DecimalField(decimal_places=0, default=60, help_text='Delivery charge inside Dhaka', max_digits=5)),
                ('delivery_charge_outside', models.DecimalField(decimal_places=0, default=120, help_text='Delivery charge outside Dhaka', max_digits=5)),
                ('facebook_page_url', models.URLField(blank=True, default='https://facebook.com', help_text='Full URL to your Facebook Page', null=True)),
                ('messenger_username', models.CharField(blank=True, help_text="Your Page Username or ID (e.g. 'JebaEnterprise')", max_length=50, null=True)),
                ('meta_pixel_id', models.CharField(blank=True, help_text="Your Meta Pixel ID (e.g. '1234567890')", max_length=50, null=True)),
                ('meta_access_token', models.TextField(blank=True, help_text='Long Access Token from Events Manager > Settings > Conversions API', null=True)),
                ('contact_phone', models.CharField(default='+880 1771-000000', help_text='Support Phone Number', max_length=20)),
                ('contact_email', models.EmailField(default='jebaenterprisebd@gmail.com', help_text='Support Email', max_length=254)),
                ('contact_address', models.TextField(default='H# 00/00, AAAAA, AAAAA, AAAA', help_text='Physical Office Address')),
                ('business_hours', models.CharField(default='Sat - Thu: 10:00 AM - 8:00 PM', help_text='e.g. Sat-Thu 10am-8pm', max_length=100)),
                ('whatsapp_number', models.CharField(default='8801716330967', help_text='WhatsApp number for direct contact (Start with country code, e.g., 88017...).', max_length=20)),
                ('contact_message_template', models.TextField(default='আমি [PRODUCT_NAME] সম্পর্কে বিস্তারিত তথ্য জানতে আগ্রহী। প্রোডাক্ট লিংক: [PRODUCT_LINK]', help_text='Bengali message template. Use [PRODUCT_NAME] and [PRODUCT_LINK] placeholders.')),
                ('call_for_price', models.BooleanField(default=False, help_text="If checked, price will be hidden and 'Contact for Price' shown.")),
                ('maintenance_mode', models.BooleanField(default=False, help_text="If checked, the entire site (except admin) will show the 'Under Maintenance' page.")),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
                'db_table': 'products_sitesettings',
            },
        ),
    ]
