# Generated by Django 5.2.8 on 2025-11-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_core', '0001_initial'),
        ('jeba_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='featured_products',
            field=models.ManyToManyField(blank=True, help_text="Select specific products to display in the Homepage Hero Slider. If empty, the system will use products marked 'Is Featured'.", related_name='featured_in_hero', to='jeba_inventory.product', verbose_name='Hero Section Products'),
        ),
    ]
