# Generated by Django 5.2.8 on 2025-12-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_core', '0002_sitesettings_featured_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Browser Favicon', null=True, upload_to='site/branding/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_scripts',
            field=models.TextField(blank=True, default='', help_text='Scripts to inject before </body> like Chat Widgets.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_scripts',
            field=models.TextField(blank=True, default='', help_text='Scripts to inject in <head> like Google Analytics, Pixel Base Code, etc.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Main Website Logo', null=True, upload_to='site/branding/'),
        ),
    ]
