# Generated by Django 5.2.8 on 2025-11-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Jeba Enterprise', max_length=100)),
                ('default_meta_title', models.CharField(help_text='Fallback title', max_length=60)),
                ('default_meta_description', models.CharField(help_text='Fallback description', max_length=160)),
                ('default_social_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
            ],
            options={
                'verbose_name': 'Global SEO Settings',
                'verbose_name_plural': 'Global SEO Settings',
            },
        ),
        migrations.CreateModel(
            name='StaticPageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(choices=[('home', 'Home Page'), ('about', 'About Us'), ('contact', 'Contact Us'), ('login', 'Login'), ('register', 'Register')], max_length=50, unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
            ],
        ),
    ]
