# Generated by Django 5.2.8 on 2025-11-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpageseo',
            name='is_seo_optimized',
            field=models.BooleanField(default=False, help_text='True if AI has processed this.'),
        ),
        migrations.AddField(
            model_name='staticpageseo',
            name='meta_description_ai',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='staticpageseo',
            name='meta_title_ai',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
