# Generated by Django 5.2.8 on 2025-11-29 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_seo', '0002_staticpageseo_is_seo_optimized_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEODashboard',
            fields=[
            ],
            options={
                'verbose_name': '🚀 AI Command Panel',
                'verbose_name_plural': '🚀 AI Command Panel',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('jeba_seo.globalseosettings',),
        ),
    ]
