# Generated by Django 5.2.8 on 2025-12-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_seo', '0003_seodashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalseosettings',
            name='bing_site_verification',
            field=models.CharField(blank=True, help_text='Bing Webmaster Tools verification code', max_length=100),
        ),
        migrations.AddField(
            model_name='globalseosettings',
            name='facebook_domain_verification',
            field=models.CharField(blank=True, help_text='Facebook Domain Verification code', max_length=100),
        ),
        migrations.AddField(
            model_name='globalseosettings',
            name='google_site_verification',
            field=models.CharField(blank=True, help_text='Google Search Console verification code', max_length=100),
        ),
    ]
