# Generated by Django 5.2.8 on 2025-11-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jeba_inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Blog Title')),
                ('slug', models.SlugField(help_text='URL-friendly version of the title (auto-generated). Essential for SEO.', max_length=255, unique=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/featured/')),
                ('content', models.TextField(verbose_name='Post Content')),
                ('excerpt', models.TextField(blank=True, help_text='Short summary for SEO meta descriptions and list views.', max_length=500)),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('views', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, help_text='Select products mentioned in this post to create backlinks.', related_name='blog_posts', to='jeba_inventory.product', verbose_name='Attached Products')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'db_table': 'jeba_blog_post',
                'ordering': ['-created_at'],
            },
        ),
    ]
