# Generated by Django 5.2.8 on 2025-11-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Custom meta description for search results (max 155 chars recommended).', max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Custom title tag for search results (max 60 chars recommended).', max_length=150),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Short summary for SEO meta descriptions and list views. Will auto-fill if empty.', max_length=500),
        ),
    ]
