# Generated by Django 5.2.8 on 2025-12-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_blog', '0002_blogpost_meta_description_blogpost_meta_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='featured_image_placeholder',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
