# Generated by Django 5.2.8 on 2025-11-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitorprice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='scraperpreset',
            options={},
        ),
        migrations.AddField(
            model_name='scraperpreset',
            name='image_slam_dunk',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='scraperpreset',
            name='image_weight',
            field=models.DecimalField(decimal_places=2, default=0.3, max_digits=3),
        ),
        migrations.AddField(
            model_name='scraperpreset',
            name='text_weight',
            field=models.DecimalField(decimal_places=2, default=0.7, max_digits=3),
        ),
        migrations.AlterField(
            model_name='competitorprice',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='competitorprice',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='scraperpreset',
            name='confidence_threshold',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='scraperpreset',
            name='text_slam_dunk',
            field=models.IntegerField(default=85),
        ),
    ]
