# Generated by Django 5.2.8 on 2025-11-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='manual_subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Manually set the subtotal. Leave blank to use sum of items.', max_digits=10, null=True, verbose_name='Subtotal Override'),
        ),
        migrations.AddField(
            model_name='sale',
            name='manual_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Manually set the final total. Leave blank to use Subtotal + Delivery Charge.', max_digits=10, null=True, verbose_name='Total Amount Override'),
        ),
    ]
