# Generated by Django 5.2.8 on 2025-12-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_sales', '0003_alter_sale_options_alter_sale_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Case insensitive (e.g. SALE10)', max_length=50, unique=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Flat discount amount in Taka', max_digits=10)),
                ('min_spend', models.DecimalField(decimal_places=2, default=0, help_text='Minimum cart total required', max_digits=10)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
