# Generated by Django 5.2.8 on 2025-12-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_sales', '0004_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='variant_summary',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Variant Details'),
        ),
    ]
