"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import dj_database_url
import os
from dotenv import load_dotenv
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG') == 'True'
if not DEBUG:
    # Security checks
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # Trust the proxy (Nginx) to handle the SSL/HTTPS header
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',


    # --- NEW MODULAR APPS ---
    'jeba_seo',
    'jeba_core',
    'jeba_inventory',
    'jeba_sales',
    'jeba_accounts',
    'jeba_engagement',
    'jeba_intelligence',
    'jeba_analytics',
    'jeba_blog',
    'jeba_landing',
    # --- EXISTING APP (Deprecated/Hidden) ---
    # 'products', 
    'import_export',    
    # --- ADD THIS LINE ---
    'django.contrib.humanize', 
    # ---------------------
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # --- ADD THIS LINE HERE (Must be after SessionMiddleware) ---
    'django.middleware.locale.LocaleMiddleware', 
    # --------------------------
    # --- ADD THIS LINE HERE ---
    'jeba_analytics.middleware.AnalyticsMiddleware',
    # --------------------------
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # --- Maintenance Mode Middleware ---
    'jeba_core.middleware.MaintenanceModeMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Updated to use new modular app's context processor
                'jeba_core.context_processors.global_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_TZ = True

# --- ADD THESE I18N SETTINGS ---
LANGUAGES = [
    ('en', _('English')),
    ('bn', _('Bengali')),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]
# -------------------------------

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media files (User-uploaded content)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# --- LOGGING ---
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO', 
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'jebaenterprise.log', 
            'formatter': 'verbose', 
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'jeba_inventory': { # Updated logger name
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# --- AUTHENTICATION SETTINGS ---
LOGIN_REDIRECT_URL = '/'          
LOGOUT_REDIRECT_URL = '/'         


# --- JAZZMIN WORLD-CLASS DARK THEME SETTINGS ---

JAZZMIN_SETTINGS = {
    "site_header": "Jeba Enterprise",
    "site_brand": "Jeba Admin",
    "site_logo": "logo.svg", 
    "site_logo_classes": "img-circle",
    "welcome_sign": "Welcome to Jeba Enterprise HQ",
    "copyright": "Jeba Enterprise Ltd",
    "search_model": ["jeba_inventory.Product", "jeba_sales.Sale"],
    "user_avatar": None,

    # Top Menu
    "topmenu_links": [
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "View Site", "url": "/", "new_window": True},
    ],

    # User Menu
    "usermenu_links": [
        {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
        {"model": "auth.user"}
    ],

    # Side Menu
    "show_sidebar": True,
    "navigation_expanded": True,
    
    # Icons (Updated for Modular Apps)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        
        "jeba_core.SiteSettings": "fas fa-cogs",
        "jeba_inventory.Product": "fas fa-box-open",
        "jeba_inventory.Category": "fas fa-tags",
        "jeba_inventory.ProductVariation": "fas fa-sliders-h",
        "jeba_sales.Sale": "fas fa-shopping-cart",
        "jeba_accounts.UserProfile": "fas fa-address-card",
        "jeba_engagement.Review": "fas fa-star",
        "jeba_engagement.Wishlist": "fas fa-heart",
        "jeba_intelligence": "fas fa-brain",
        "jeba_analytics": "fas fa-chart-line",
        "jeba_blog": "fas fa-newspaper",
        "jeba_landing.LandingPage": "fas fa-rocket",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    
    "custom_links": {
        "jeba_intelligence": [{
            "name": "Competitor Analysis", 
            "url": "admin_scraper", 
            "icon": "fas fa-search-dollar",
        }]
    },
}

# --- UI TWEAKS FOR WORLD-CLASS DARK THEME ---
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    
    # Dark Theme Colors
    "brand_colour": "navbar-dark",
    "accent": "accent-info", 
    "navbar": "navbar-dark navbar-primary", 
    "no_navbar_border": True,
    "navbar_fixed": True, 
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True, 
    
    # Dark Sidebar
    "sidebar": "sidebar-dark-primary", 
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    
    "theme": "darkly", 
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "login_logo_classes": "text-center",
    "login_logo": "media/logo.svg" 
}

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

# Sessions
SESSION_ENGINE = "django.contrib.sessions.backends.file"
SESSION_FILE_PATH = BASE_DIR / "sessions"

# Steadfast API
STEADFAST_API_KEY = os.getenv('STEADFAST_API_KEY')
STEADFAST_SECRET_KEY = os.getenv('STEADFAST_SECRET_KEY')
STEADFAST_BASE_URL = 'https://portal.packzy.com/api/v1'

# Import Export
IMPORT_EXPORT_USE_TRANSACTIONS = True

# Maintenance Mode
MAINTENANCE_MODE = os.getenv('MAINTENANCE_MODE', 'False') == 'True'
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')