# Generated by Django 5.2.8 on 2025-11-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productevent',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Event Metadata'),
        ),
        migrations.AddField(
            model_name='searchevent',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Event Metadata'),
        ),
        migrations.AlterField(
            model_name='productevent',
            name='event_type',
            field=models.CharField(choices=[('VIEW', 'Product View'), ('CART', 'Added to Cart'), ('PURCHASE', 'Purchased'), ('SHARE', 'Shared'), ('CONTACT', 'Contact Click'), ('CHECKOUT', 'Initiated Checkout')], max_length=20),
        ),
    ]
