# Generated by Django 5.2.8 on 2025-11-26 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_analytics', '0002_productevent_metadata_searchevent_metadata_and_more'),
        ('jeba_inventory', '0002_tag_product_is_active_product_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAnalytics',
            fields=[
            ],
            options={
                'verbose_name': 'Product Analytics (Winning Products)',
                'verbose_name_plural': 'Product Analytics (Winning Products)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('jeba_inventory.product',),
        ),
    ]
