# Generated by Django 5.2.8 on 2025-11-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_analytics', '0004_alter_productevent_options_alter_searchevent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAdSpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Spend Date')),
                ('facebook_spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Facebook Ads (Tk)')),
                ('google_spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Google Ads (Tk)')),
                ('tiktok_spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='TikTok/Other (Tk)')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12)),
                ('total_orders', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Daily Marketing & ROI',
                'verbose_name_plural': 'Daily Marketing & ROI',
                'db_table': 'jeba_analytics_adspend',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='productanalytics',
            options={'verbose_name': 'Winning Product Analysis', 'verbose_name_plural': 'Winning Product Analysis'},
        ),
        migrations.AlterModelOptions(
            name='productevent',
            options={'verbose_name': 'Product Interaction'},
        ),
        migrations.AlterModelOptions(
            name='searchevent',
            options={'verbose_name': 'Search Log', 'verbose_name_plural': 'Search Logs'},
        ),
        migrations.AddField(
            model_name='productevent',
            name='value_at_event',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Product selling price at the moment of this event.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='searchevent',
            name='result_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Results Found'),
        ),
        migrations.AlterField(
            model_name='productevent',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='searchevent',
            name='query',
            field=models.CharField(max_length=255, verbose_name='Search Query'),
        ),
    ]
