# Generated by Django 5.2.8 on 2025-11-27 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_analytics', '0005_dailyadspend_alter_productanalytics_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productanalytics',
            options={'verbose_name': 'Product Funnel & Analytics', 'verbose_name_plural': 'Product Funnel & Analytics'},
        ),
    ]
