# Generated by Django 5.2.8 on 2025-11-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_analytics', '0006_alter_productanalytics_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productevent',
            name='load_time',
            field=models.FloatField(blank=True, help_text='Page load time in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='productevent',
            name='scroll_depth',
            field=models.PositiveIntegerField(default=0, help_text='Max scroll percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='stock_status_at_view',
            field=models.BooleanField(default=True, help_text='Was the product in stock when viewed?'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='time_on_page',
            field=models.PositiveIntegerField(default=0, help_text='Time spent on page in seconds'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productevent',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productevent',
            name='utm_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='searchevent',
            name='utm_campaign',
            field=models.CharField(blank=True, help_text='Campaign Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='searchevent',
            name='utm_medium',
            field=models.CharField(blank=True, help_text='Medium (e.g. cpc, email)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='searchevent',
            name='utm_source',
            field=models.CharField(blank=True, help_text='Source (e.g. facebook, google)', max_length=50, null=True),
        ),
    ]
