# Generated by Django 5.2.8 on 2025-12-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_analytics', '0007_productevent_load_time_productevent_scroll_depth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('url', models.CharField(max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(default='desktop', max_length=20)),
                ('load_time_ms', models.IntegerField(blank=True, help_text='Full Page Load', null=True)),
                ('ttfb_ms', models.IntegerField(blank=True, help_text='Time to First Byte', null=True)),
                ('max_scroll', models.PositiveIntegerField(default=0)),
                ('is_bounce', models.BooleanField(default=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('raw_data', models.JSONField(default=dict, verbose_name='Full Telemetry Blob')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Session Trace',
                'verbose_name_plural': 'Session Traces',
                'ordering': ['-created_at'],
            },
        ),
    ]
