# Generated by Django 5.2.8 on 2025-12-03 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jeba_inventory', '0008_product_use_ai_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('default_config', models.JSONField(blank=True, default=dict)),
                ('base_css', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('theme_preset', models.CharField(blank=True, max_length=20, null=True)),
                ('override_primary_color', models.CharField(blank=True, max_length=20, null=True)),
                ('override_accent_color', models.CharField(blank=True, max_length=20, null=True)),
                ('custom_css', models.TextField(blank=True, null=True)),
                ('font_heading', models.CharField(blank=True, default='Montserrat', max_length=50)),
                ('font_body', models.CharField(blank=True, default='Open Sans', max_length=50)),
                ('countdown_end', models.DateTimeField(blank=True, null=True)),
                ('stock_warning', models.IntegerField(default=0)),
                ('trust_badge_image', models.ImageField(blank=True, null=True, upload_to='landing/badges/')),
                ('meta_pixel_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing_pages', to='jeba_inventory.product')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jeba_landing.landingtheme')),
            ],
        ),
        migrations.CreateModel(
            name='LandingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('HERO', 'Hero Section'), ('VIDEO', 'Video Section'), ('FEATURES_GRID', 'Features Grid'), ('TEXT_IMAGE_SPLIT', 'Split Content'), ('CAROUSEL', 'Image Carousel'), ('RICH_TEXT', 'Rich Text Block'), ('TESTIMONIALS', 'Testimonials'), ('FAQ', 'FAQ Accordion')], default='TEXT_IMAGE_SPLIT', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('icon_class', models.CharField(blank=True, max_length=100, null=True)),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('subheading', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('text_alignment', models.CharField(default='center', max_length=20)),
                ('padding_top', models.IntegerField(default=80)),
                ('padding_bottom', models.IntegerField(default=80)),
                ('background_color', models.CharField(blank=True, max_length=20, null=True)),
                ('background_gradient', models.CharField(blank=True, max_length=200, null=True)),
                ('text_color', models.CharField(blank=True, max_length=20, null=True)),
                ('overlay_opacity', models.CharField(default='0.4', max_length=5)),
                ('divider_top', models.CharField(default='NONE', max_length=20)),
                ('divider_bottom', models.CharField(default='NONE', max_length=20)),
                ('border_radius', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='landing/images/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='landing/videos/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='landing/images/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='landing/images/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='landing/images/')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='landing/images/')),
                ('animation_effect', models.CharField(default='FADE_UP', max_length=20)),
                ('ai_generated', models.BooleanField(default=False)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='jeba_landing.landingpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
