# Generated by Django 5.2.8 on 2025-12-13 17:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jeba_inventory', '0012_alter_product_is_active_alter_product_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_pixel_id', models.CharField(blank=True, help_text='Specific Pixel for this campaign (overrides global)', max_length=50)),
                ('currency', models.CharField(choices=[('BDT', 'Taka'), ('USD', 'USD')], default='BDT', max_length=10)),
                ('language_toggle', models.BooleanField(default=True, help_text='Allow users to switch between BN/EN')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_campaigns', to='jeba_inventory.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="e.g. 'Control', 'Video Hero'", max_length=100)),
                ('weight', models.PositiveIntegerField(default=50, help_text='Traffic percentage (0-100)')),
                ('primary_color', models.CharField(default='#D4F759', max_length=20)),
                ('accent_color', models.CharField(default='#000000', max_length=20)),
                ('enable_fomo_timer', models.BooleanField(default=False)),
                ('fomo_timer_end', models.DateTimeField(blank=True, null=True)),
                ('enable_social_proof', models.BooleanField(default=True, help_text="Show 'X people viewing now'")),
                ('enable_exit_popup', models.BooleanField(default=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='jeba_landing.campaign')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('HERO_CAROUSEL', 'Hero Carousel'), ('HERO_VIDEO', 'Hero Video'), ('FEATURES', 'Features Grid'), ('PRODUCT_HIGHLIGHT', 'Product Highlight (Split)'), ('TESTIMONIALS', 'Testimonials'), ('FAQ', 'FAQ Accordion'), ('CTA_Sticky', 'Sticky Bottom CTA'), ('HTML', 'Raw HTML')], max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('content', models.JSONField(blank=True, default=dict, help_text='JSON structure for the section content')),
                ('is_dark_mode', models.BooleanField(default=False)),
                ('padding_y', models.CharField(default='py-12', max_length=20)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='jeba_landing.campaignvariant')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(default='mobile', max_length=20)),
                ('country', models.CharField(default='Bangladesh', max_length=50)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('referrer_url', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='jeba_landing.campaign')),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='jeba_landing.campaignvariant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConversionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('PAGE_VIEW', 'Page View'), ('SCROLL_50', 'Scrolled 50%'), ('SCROLL_90', 'Scrolled 90%'), ('CLICK_CTA', 'Clicked CTA'), ('ADD_TO_CART', 'Added to Cart'), ('INITIATE_CHECKOUT', 'Initiated Checkout'), ('PURCHASE', 'Purchase Completed'), ('EXIT_INTENT', 'Exit Intent Triggered'), ('HEARTBEAT', 'Time on Page (Heartbeat)')], max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra data like button text, scroll depth, or product ID')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, help_text='Monetary value if applicable', max_digits=10)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='jeba_landing.visitorsession')),
            ],
            options={
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='jeba_landin_event_t_7a854d_idx')],
            },
        ),
    ]
