# Generated by Django 5.2.8 on 2025-11-28 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jeba_inventory', '0002_tag_product_is_active_product_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internal title for this campaign page', max_length=255)),
                ('slug', models.SlugField(help_text="URL path, e.g., 'super-sale-watch'", max_length=255, unique=True)),
                ('meta_pixel_id', models.CharField(blank=True, help_text='Override the global pixel ID for this specific campaign', max_length=50, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing_pages', to='jeba_inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='LandingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('HERO', 'Hero Section (Full Screen)'), ('VIDEO', 'Cinematic Video'), ('FEATURES_GRID', 'Features Grid (Icons)'), ('PARALLAX_IMG', 'Parallax Image Scroll'), ('TEXT_IMAGE_SPLIT', 'Split Content (Text + Image)'), ('SPECS', 'Specification Table'), ('TESTIMONIALS', 'Testimonials Carousel'), ('CTA_FOOTER', 'Call to Action Footer')], default='TEXT_IMAGE_SPLIT', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of appearance (0 is top)')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('subheading', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, help_text='Main text content for this section', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='landing/images/')),
                ('video_file', models.FileField(blank=True, help_text='Upload MP4 for background or player', null=True, upload_to='landing/videos/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube/Vimeo link if not uploading file', null=True)),
                ('background_color', models.CharField(default='#000000', help_text='Hex code (e.g. #000000)', max_length=20)),
                ('text_color', models.CharField(default='#FFFFFF', help_text='Hex code (e.g. #FFFFFF)', max_length=20)),
                ('animation_effect', models.CharField(choices=[('NONE', 'No Animation'), ('FADE_UP', 'Fade In Up'), ('FADE_IN', 'Fade In Simple'), ('ZOOM_IN', 'Zoom In'), ('SLIDE_LEFT', 'Slide In from Left'), ('SLIDE_RIGHT', 'Slide In from Right')], default='FADE_UP', max_length=20)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='jeba_landing.landingpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
