# Generated by Django 5.2.8 on 2025-12-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='manual_ai_prompt',
            field=models.TextField(blank=True, help_text='Paste AI-generated JSON here to auto-create variants/sections.', null=True),
        ),
    ]
