# Generated by Django 5.2.8 on 2025-11-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingsection',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='landing/images/', verbose_name='Carousel Image 2'),
        ),
        migrations.AddField(
            model_name='landingsection',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='landing/images/', verbose_name='Carousel Image 3'),
        ),
        migrations.AddField(
            model_name='landingsection',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='landing/images/', verbose_name='Carousel Image 4'),
        ),
        migrations.AddField(
            model_name='landingsection',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='landing/images/', verbose_name='Carousel Image 5'),
        ),
        migrations.AlterField(
            model_name='landingsection',
            name='section_type',
            field=models.CharField(choices=[('HERO', 'Hero Section (Full Screen)'), ('VIDEO', 'Cinematic Video'), ('FEATURES_GRID', 'Features Grid (Icons)'), ('TEXT_IMAGE_SPLIT', 'Split Content (Text + Image)'), ('CAROUSEL', 'Image Carousel (Slider)')], default='TEXT_IMAGE_SPLIT', max_length=50),
        ),
    ]
