# Generated by Django 5.2.8 on 2025-12-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingsection',
            name='desktop_media_position',
            field=models.CharField(default='50% 50%', help_text="X Y coordinates for Desktop image focus (e.g. '50% 20%')", max_length=50),
        ),
        migrations.AddField(
            model_name='landingsection',
            name='mobile_media_position',
            field=models.CharField(default='50% 50%', help_text='X Y coordinates for Mobile image focus', max_length=50),
        ),
    ]
