# Generated by Django 5.2.8 on 2025-12-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_landing', '0002_landingsection_desktop_media_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingsection',
            name='design_variant',
            field=models.CharField(choices=[('OVERLAY', 'Full Screen Overlay (Default)'), ('SPLIT_LEFT', 'Split: Text Left / Image Right'), ('SPLIT_RIGHT', 'Split: Text Right / Image Left'), ('MINIMAL', 'Minimal Center (No Background Image)')], default='OVERLAY', help_text='Controls the layout style (e.g. Split Screen vs Overlay)', max_length=50),
        ),
    ]
