# Generated by Django 5.2.8 on 2025-11-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_landing', '0002_landingsection_image_2_landingsection_image_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingsection',
            name='button_text',
            field=models.CharField(blank=True, help_text="Override the default button text (e.g. 'Get 50% Off'). Leave empty for default.", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='landingsection',
            name='overlay_opacity',
            field=models.CharField(choices=[('0.0', 'No Overlay (Original Image)'), ('0.2', 'Light Shadow (0.2)'), ('0.4', 'Medium Shadow (0.4)'), ('0.6', 'Dark Shadow (0.6 - Recommended for Light Text)'), ('0.8', 'Very Dark (0.8)')], default='0.4', help_text='Darkens the background image to make text readable.', max_length=5),
        ),
        migrations.AddField(
            model_name='landingsection',
            name='text_alignment',
            field=models.CharField(choices=[('center', 'Center (Default)'), ('start', 'Left Aligned'), ('end', 'Right Aligned')], default='center', help_text='Where should the text be positioned?', max_length=20),
        ),
        migrations.AlterField(
            model_name='landingsection',
            name='image',
            field=models.ImageField(blank=True, help_text="<b>HERO GUIDE:</b> Recommended 1920x1080px (Landscape). Keep the center/sides clear if you align text there. Use 'Overlay Opacity' to make text pop.", null=True, upload_to='landing/images/'),
        ),
    ]
