# Generated by Django 5.2.8 on 2025-11-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_landing', '0003_landingsection_button_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingsection',
            name='image',
            field=models.ImageField(blank=True, help_text="<b>HERO GUIDE:</b> Recommended 1920x1080px (Landscape). If using 'Left Aligned' text, pick an image with space on the left. Use 'Overlay Opacity' to fix readability issues.", null=True, upload_to='landing/images/'),
        ),
        migrations.AlterField(
            model_name='landingsection',
            name='overlay_opacity',
            field=models.CharField(choices=[('0.0', 'No Overlay (Original Image)'), ('0.2', 'Light Shadow (20%)'), ('0.4', 'Medium Shadow (40% - Recommended)'), ('0.6', 'Dark Shadow (60%)'), ('0.8', 'Deep Shadow (80% - For Light Text)')], default='0.4', help_text='Darkens the background image to make text readable.', max_length=5),
        ),
    ]
