# Generated by Django 5.2.8 on 2025-12-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_landing', '0003_landingsection_design_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingsection',
            name='design_variant',
            field=models.CharField(choices=[('OVERLAY', 'Full Screen Overlay (Default)'), ('SPLIT_LEFT', 'Split: Text Left / Image Right'), ('SPLIT_RIGHT', 'Split: Text Right / Image Left'), ('MINIMAL', 'Minimal Center (No Background Image)'), ('PRODUCT_FOCUS', 'Product Focus (Mobile First / Modern)')], default='OVERLAY', help_text='Controls the layout style (e.g. Split Screen vs Overlay)', max_length=50),
        ),
    ]
