# Generated by Django 5.2.8 on 2025-12-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_landing', '0004_alter_landingsection_design_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingsection',
            name='foreground_image',
            field=models.ImageField(blank=True, help_text='Custom Image/GIF to layer ON TOP of the background. Overrides product image.', null=True, upload_to='landing/foreground/'),
        ),
        migrations.AddField(
            model_name='landingsection',
            name='foreground_video',
            field=models.FileField(blank=True, help_text='Custom Video (MP4) to layer ON TOP of the background. Overrides images.', null=True, upload_to='landing/foreground/'),
        ),
        migrations.AlterField(
            model_name='landingsection',
            name='design_variant',
            field=models.CharField(choices=[('OVERLAY', 'Full Screen Overlay (Default)'), ('SPLIT_LEFT', 'Split: Text Left / Image Right'), ('SPLIT_RIGHT', 'Split: Text Right / Image Left'), ('MINIMAL', 'Minimal Center (No Background Image)'), ('PRODUCT_FOCUS', 'Product Focus (Mobile First / Modern)')], default='OVERLAY', help_text='Controls the layout style', max_length=50),
        ),
        migrations.AlterField(
            model_name='landingsection',
            name='desktop_media_position',
            field=models.CharField(default='50% 50%', max_length=50),
        ),
        migrations.AlterField(
            model_name='landingsection',
            name='image',
            field=models.ImageField(blank=True, help_text='Background Image for Hero, or Side Image for Split.', null=True, upload_to='landing/images/'),
        ),
        migrations.AlterField(
            model_name='landingsection',
            name='mobile_media_position',
            field=models.CharField(default='50% 50%', max_length=50),
        ),
    ]
