# Generated by Django 5.2.8 on 2025-11-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_landing', '0004_alter_landingsection_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='accent_color',
            field=models.CharField(default='#D4F759', help_text='Buttons, Icons, and Highlights', max_length=20),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='font_body',
            field=models.CharField(choices=[('Montserrat', 'Montserrat (Modern & Bold)'), ('Open Sans', 'Open Sans (Clean & Neutral)'), ('Roboto', 'Roboto (Tech & Sharp)'), ('Playfair Display', 'Playfair Display (Luxury & Serif)'), ('Lato', 'Lato (Friendly)'), ('Oswald', 'Oswald (Strong Headers)'), ('Raleway', 'Raleway (Elegant)')], default='Open Sans', help_text='Font for regular text', max_length=50),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='font_heading',
            field=models.CharField(choices=[('Montserrat', 'Montserrat (Modern & Bold)'), ('Open Sans', 'Open Sans (Clean & Neutral)'), ('Roboto', 'Roboto (Tech & Sharp)'), ('Playfair Display', 'Playfair Display (Luxury & Serif)'), ('Lato', 'Lato (Friendly)'), ('Oswald', 'Oswald (Strong Headers)'), ('Raleway', 'Raleway (Elegant)')], default='Montserrat', help_text='Font for Headlines', max_length=50),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='primary_color',
            field=models.CharField(default='#000000', help_text='Main Background Color', max_length=20),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='secondary_color',
            field=models.CharField(default='#1d1d1f', help_text='Card/Section Background Color', max_length=20),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='text_color',
            field=models.CharField(default='#FFFFFF', help_text='Global Text Color', max_length=20),
        ),
        migrations.AddField(
            model_name='landingsection',
            name='background_gradient',
            field=models.CharField(blank=True, help_text="CSS Gradient (e.g., 'linear-gradient(45deg, #ff0000, #0000ff)')", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='landingsection',
            name='border_radius',
            field=models.IntegerField(default=0, help_text='Round corners for inner cards/images (px)'),
        ),
        migrations.AddField(
            model_name='landingsection',
            name='divider_bottom',
            field=models.CharField(choices=[('NONE', 'None'), ('WAVE', 'Organic Wave'), ('SLANT_RIGHT', 'Sharp Slant (Right)'), ('SLANT_LEFT', 'Sharp Slant (Left)'), ('CURVE', 'Smooth Curve'), ('ARROW', 'Arrow Down')], default='NONE', help_text='Shape separator at the bottom', max_length=20),
        ),
        migrations.AddField(
            model_name='landingsection',
            name='divider_top',
            field=models.CharField(choices=[('NONE', 'None'), ('WAVE', 'Organic Wave'), ('SLANT_RIGHT', 'Sharp Slant (Right)'), ('SLANT_LEFT', 'Sharp Slant (Left)'), ('CURVE', 'Smooth Curve'), ('ARROW', 'Arrow Down')], default='NONE', help_text='Shape separator at the top', max_length=20),
        ),
        migrations.AddField(
            model_name='landingsection',
            name='icon_class',
            field=models.CharField(blank=True, help_text="FontAwesome class (e.g., 'fa-solid fa-rocket')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landingsection',
            name='padding_bottom',
            field=models.IntegerField(default=80, help_text='Padding Bottom (px)'),
        ),
        migrations.AddField(
            model_name='landingsection',
            name='padding_top',
            field=models.IntegerField(default=80, help_text='Padding Top (px)'),
        ),
        migrations.AlterField(
            model_name='landingsection',
            name='background_color',
            field=models.CharField(blank=True, help_text='Hex Color (Overrides Global)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='landingsection',
            name='button_text',
            field=models.CharField(blank=True, help_text="Override button text (e.g. 'Get 50% Off'). Leave empty for default.", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='landingsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='landing/images/'),
        ),
        migrations.AlterField(
            model_name='landingsection',
            name='overlay_opacity',
            field=models.CharField(choices=[('0.0', '0%'), ('0.2', '20%'), ('0.4', '40%'), ('0.6', '60%'), ('0.8', '80%'), ('0.9', '90%')], default='0.4', help_text='Darkens background image for readability.', max_length=5),
        ),
        migrations.AlterField(
            model_name='landingsection',
            name='section_type',
            field=models.CharField(choices=[('HERO', 'Hero Section (Full Screen)'), ('VIDEO', 'Cinematic Video'), ('FEATURES_GRID', 'Features Grid (Icons)'), ('TEXT_IMAGE_SPLIT', 'Split Content (Text + Image)'), ('CAROUSEL', 'Image Carousel (Slider)'), ('RICH_TEXT', 'Rich Text / HTML Block')], default='TEXT_IMAGE_SPLIT', max_length=50),
        ),
        migrations.AlterField(
            model_name='landingsection',
            name='text_alignment',
            field=models.CharField(choices=[('center', 'Center (Default)'), ('start', 'Left Aligned'), ('end', 'Right Aligned')], default='center', max_length=20),
        ),
        migrations.AlterField(
            model_name='landingsection',
            name='text_color',
            field=models.CharField(blank=True, help_text='Text Color (Overrides Global)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='landingsection',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload MP4', null=True, upload_to='landing/videos/'),
        ),
        migrations.AlterField(
            model_name='landingsection',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube/Vimeo link', null=True),
        ),
    ]
