# Generated by Django 5.2.8 on 2025-12-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_landing', '0005_landingsection_foreground_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingsection',
            name='text_content_padding',
            field=models.IntegerField(default=0, help_text='Padding around the text content (in pixels). Helps fix border issues.'),
        ),
    ]
