# Generated by Django 5.2.8 on 2025-12-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_landing', '0006_landingsection_text_content_padding'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingsection',
            name='media_max_width',
            field=models.CharField(default='100%', help_text="e.g. '400px', '80%', or '50vh'. Controls hero image/video size.", max_length=20),
        ),
        migrations.AddField(
            model_name='landingsection',
            name='media_padding',
            field=models.CharField(default='0px', help_text="Padding around the media (e.g. '20px').", max_length=20),
        ),
        migrations.AddField(
            model_name='landingsection',
            name='media_vertical_offset',
            field=models.IntegerField(default=0, help_text='Move image UP or DOWN in pixels (e.g. -50 to move up, 20 to move down).'),
        ),
    ]
