# Generated by Django 5.2.8 on 2025-12-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_landing', '0007_landingsection_media_max_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingsection',
            name='badge_label',
            field=models.CharField(blank=True, help_text="e.g. 'Best Seller', 'New Arrival' - Shows as a floating badge on the hero image.", max_length=50, null=True),
        ),
    ]
