# Generated by Django 5.2.8 on 2025-12-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_landing', '0008_landingsection_badge_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingsection',
            name='placeholders',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
