# Generated by Django 5.2.8 on 2025-12-05 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL of image sent by user', null=True),
        ),
    ]
