# Generated by Django 5.2.8 on 2025-12-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_messenger', '0002_message_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='profile_pic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='image_url',
            field=models.TextField(blank=True, help_text='URL of image sent by user', null=True),
        ),
    ]
