# Generated by Django 5.2.8 on 2025-12-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_messenger', '0003_alter_conversation_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='notes',
            field=models.TextField(blank=True, help_text='Admin private notes', null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='saved_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='saved_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='sentiment',
            field=models.CharField(choices=[('hot', '🔥 Hot Lead'), ('warm', '😊 Interested'), ('cold', '❄️ Just Browsing'), ('angry', '😡 Complaint'), ('neutral', '😐 Neutral')], default='neutral', max_length=20),
        ),
    ]
