# Generated by Django 5.2.8 on 2025-12-05 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_messenger', '0004_conversation_notes_conversation_saved_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessengerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_auto_ai', models.BooleanField(default=False, help_text='If checked, AI will automatically generate suggestions for every new message. Uncheck to save API costs.', verbose_name='Enable Auto AI Research')),
            ],
            options={
                'verbose_name': 'Messenger Settings',
                'verbose_name_plural': 'Messenger Settings',
            },
        ),
    ]
