# Generated by Django 5.2.8 on 2025-12-04 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('compiled_html', models.TextField(blank=True, help_text='The full, raw HTML of the page.')),
                ('compiled_css', models.TextField(blank=True, help_text='Custom CSS specific to this page.')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('ai', 'AI Model'), ('system', 'System Context')], max_length=20)),
                ('text_prompt', models.TextField(blank=True, null=True)),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='ai_builder/refs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='jeba_ai_builder.aipage')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_snapshot', models.TextField()),
                ('css_snapshot', models.TextField(blank=True)),
                ('description', models.CharField(help_text="e.g. 'Changed hero color'", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='jeba_ai_builder.aipage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
