# Generated by Django 5.2.8 on 2025-12-04 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeba_ai_builder', '0001_initial'),
        ('jeba_inventory', '0008_product_use_ai_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aipage',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Link this page to a specific product to auto-fill content.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_pages', to='jeba_inventory.product'),
        ),
        migrations.AlterField(
            model_name='pageversion',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
