# Generated by Django 5.2.8 on 2025-11-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_sale_saleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='buying_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
