# Generated by Django 5.2.8 on 2025-11-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_saleitem_buying_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='box_quantity',
            field=models.PositiveIntegerField(default=1, help_text='How many products are in a box'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
