# Generated by Django 5.2.8 on 2025-11-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_review_userprofile_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Check this to show on Homepage Hero section'),
        ),
    ]
