# Generated by Django 5.2.8 on 2025-11-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='transparent_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/transparent/'),
        ),
    ]
