# Generated by Django 5.2.8 on 2025-11-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productimage_transparent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='transparent_image',
            field=models.ImageField(blank=True, help_text='Upload a PNG with no background here (Optional)', null=True, upload_to='products/transparent/'),
        ),
    ]
