# Generated by Django 5.2.8 on 2025-11-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_sale_payment_method_sale_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=60.0, max_digits=6),
        ),
    ]
