# Generated by Django 5.2.8 on 2025-11-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_sale_delivery_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='consignment_id',
            field=models.IntegerField(blank=True, help_text='Steadfast Consignment ID', null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='tracking_code',
            field=models.CharField(blank=True, help_text='Steadfast Tracking Code', max_length=50, null=True),
        ),
    ]
