# Generated by Django 5.2.8 on 2025-11-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_sale_consignment_id_sale_tracking_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bkash_number', models.CharField(default='017XXXXXXXX', help_text='Personal bKash Number for manual payments', max_length=15)),
                ('delivery_charge_inside', models.DecimalField(decimal_places=0, default=60, help_text='Delivery charge inside Dhaka', max_digits=5)),
                ('delivery_charge_outside', models.DecimalField(decimal_places=0, default=120, help_text='Delivery charge outside Dhaka', max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
