# Generated by Django 5.2.8 on 2025-11-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_page_url',
            field=models.URLField(blank=True, default='https://facebook.com', help_text='Full URL to your Facebook Page', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='messenger_username',
            field=models.CharField(blank=True, help_text="Your Page Username or ID (e.g. 'JebaEnterprise')", max_length=50, null=True),
        ),
    ]
