# Generated by Django 5.2.8 on 2025-11-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_sitesettings_facebook_page_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='meta_pixel_id',
            field=models.CharField(blank=True, help_text="Your Meta Pixel ID (e.g. '1234567890')", max_length=50, null=True),
        ),
    ]
