# Generated by Django 5.2.8 on 2025-11-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_sitesettings_meta_pixel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='meta_access_token',
            field=models.TextField(blank=True, help_text='Long Access Token from Events Manager > Settings > Conversions API', null=True),
        ),
    ]
