# Generated by Django 5.2.8 on 2025-11-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_sitesettings_meta_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='call_for_price',
            field=models.BooleanField(default=False, help_text="If checked, price will be hidden and 'Call for Price' shown."),
        ),
    ]
