# Generated by Django 5.2.8 on 2025-11-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_product_call_for_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='business_hours',
            field=models.CharField(default='Sat - Thu: 10:00 AM - 8:00 PM', help_text='e.g. Sat-Thu 10am-8pm', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_address',
            field=models.TextField(default='H# 00/00, AAAAA, AAAAA, AAAA', help_text='Physical Office Address'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='jebaenterprisebd@gmail.com', help_text='Support Email', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(default='+880 1771-000000', help_text='Support Phone Number', max_length=20),
        ),
    ]
