# Generated by Django 5.2.8 on 2025-11-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_sitesettings_business_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_message_template',
            field=models.TextField(default='আমি [PRODUCT_NAME] সম্পর্কে বিস্তারিত তথ্য জানতে আগ্রহী। প্রোডাক্ট লিংক: [PRODUCT_LINK]', help_text='Bengali message template. Use [PRODUCT_NAME] and [PRODUCT_LINK] placeholders.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(default='8801771298725', help_text='WhatsApp number for direct contact (Start with country code, e.g., 88017...).', max_length=20),
        ),
    ]
