# Generated by Django 5.2.8 on 2025-11-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_sitesettings_contact_message_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='call_for_price',
            field=models.BooleanField(default=False, help_text="If checked, price will be hidden and 'Contact for Price' shown."),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(default='8801716330967', help_text='WhatsApp number for direct contact (Start with country code, e.g., 88017...).', max_length=20),
        ),
    ]
