# Generated by Django 5.2.8 on 2025-11-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_sitesettings_call_for_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, help_text='Short summary shown beside the image', null=True),
        ),
    ]
