# Generated by Django 5.2.8 on 2025-11-20 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_productevent_searchevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAnalytics',
            fields=[
            ],
            options={
                'verbose_name': 'Product Analytics (Winning Products)',
                'verbose_name_plural': 'Product Analytics (Winning Products)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
    ]
