# Generated by Django 5.2.8 on 2025-11-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_productanalytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image_weight', models.DecimalField(decimal_places=2, default=0.3, max_digits=3)),
                ('text_weight', models.DecimalField(decimal_places=2, default=0.7, max_digits=3)),
                ('confidence_threshold', models.IntegerField(default=60)),
                ('text_slam_dunk', models.IntegerField(default=85)),
                ('image_slam_dunk', models.IntegerField(default=90)),
            ],
        ),
    ]
