# Generated by Django 5.2.8 on 2025-11-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_scraperpreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productevent',
            name='event_type',
            field=models.CharField(choices=[('VIEW', 'Product View'), ('CART', 'Added to Cart'), ('PURCHASE', 'Purchased'), ('SHARE', 'Shared')], max_length=20),
        ),
    ]
