# Generated by Django 5.2.8 on 2025-11-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_alter_productevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text="If checked, the entire site (except admin) will show the 'Under Maintenance' page."),
        ),
    ]
