# Generated by Django 5.2.8 on 2025-11-21 20:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_sitesettings_maintenance_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='access_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
