# Generated by Django 5.2.8 on 2025-11-21 20:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_sale_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='access_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
