# Generated by Django 5.2.8 on 2025-11-23 20:05

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_alter_sale_access_token'),
        # --- CRITICAL: DEPEND ON NEW APPS ---
        ('jeba_core', '0001_initial'),
        ('jeba_inventory', '0001_initial'),
        ('jeba_sales', '0001_initial'),
        ('jeba_accounts', '0001_initial'),
        ('jeba_engagement', '0001_initial'),
        ('jeba_intelligence', '0001_initial'),
        ('jeba_analytics', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # --- REMOVE FIELDS ---
                migrations.RemoveField(
                    model_name='product',
                    name='category',
                ),
                migrations.RemoveField(
                    model_name='competitorprice',
                    name='product',
                ),
                migrations.RemoveField(
                    model_name='saleitem',
                    name='product',
                ),
                migrations.RemoveField(
                    model_name='productvariation',
                    name='product',
                ),
                migrations.RemoveField(
                    model_name='productevent',
                    name='product',
                ),
                migrations.RemoveField(
                    model_name='wishlist',
                    name='product',
                ),
                migrations.RemoveField(
                    model_name='review',
                    name='product',
                ),
                migrations.RemoveField(
                    model_name='productimage',
                    name='product',
                ),
                migrations.RemoveField(
                    model_name='productevent',
                    name='user',
                ),
                migrations.RemoveField(
                    model_name='saleitem',
                    name='variation',
                ),
                migrations.RemoveField(
                    model_name='review',
                    name='user',
                ),
                migrations.RemoveField(
                    model_name='sale',
                    name='user',
                ),
                migrations.RemoveField(
                    model_name='saleitem',
                    name='sale',
                ),
                migrations.RemoveField(
                    model_name='searchevent',
                    name='user',
                ),
                migrations.RemoveField(
                    model_name='userprofile',
                    name='user',
                ),
                migrations.AlterUniqueTogether(
                    name='wishlist',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='wishlist',
                    name='user',
                ),
                
                # --- DELETE MODELS ---
                migrations.DeleteModel(
                    name='ScraperPreset',
                ),
                migrations.DeleteModel(
                    name='SiteSettings',
                ),
                migrations.DeleteModel(
                    name='Category',
                ),
                migrations.DeleteModel(
                    name='CompetitorPrice',
                ),
                migrations.DeleteModel(
                    name='Product',
                ),
                # --- ADDED THIS MISSING MODEL ---
                migrations.DeleteModel(
                    name='ProductAnalytics',
                ),
                # --------------------------------
                migrations.DeleteModel(
                    name='ProductImage',
                ),
                migrations.DeleteModel(
                    name='ProductEvent',
                ),
                migrations.DeleteModel(
                    name='ProductVariation',
                ),
                migrations.DeleteModel(
                    name='Review',
                ),
                migrations.DeleteModel(
                    name='Sale',
                ),
                migrations.DeleteModel(
                    name='SaleItem',
                ),
                migrations.DeleteModel(
                    name='SearchEvent',
                ),
                migrations.DeleteModel(
                    name='UserProfile',
                ),
                migrations.DeleteModel(
                    name='Wishlist',
                ),
            ],
            # --- DATABASE OPERATIONS: KEEP EMPTY ---
            database_operations=[
            ]
        )
    ]