# Generated by Django 5.2.8 on 2025-11-25 06:58

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jeba_inventory', '0001_initial'),
        ('products', '0036_remove_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAnalytics',
            fields=[
            ],
            options={
                'verbose_name': 'Product Analytics (Winning Products)',
                'verbose_name_plural': 'Product Analytics (Winning Products)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('jeba_inventory.product',),
        ),
    ]
