# Generated by Django 5.2.8 on 2025-11-26 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductAnalytics',
        ),
    ]
